application: dnh-dma
version: 1
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /report/.*|^/report$
  script: Report.app

- url: /static
  static_dir: static

- url: /public/.*|^/public$
  script: Public.app

- url: /flood_level/.*|^/flood_level$
  script: FloodLevel.app

- url: /rainfall/.*|^/rainfall$
  script: Rainfall.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: lxml
  version: latest