application: dnh-dma
version: 1
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest